#!/bin/bash

if [ "$1" == "create" ] && [ -d /opt/lampp/htdocs/NewProject ]; then
    echo "/opt/lampp/htdocs/NewProject already exits."
    echo "Please rename it to create new one !!"
    exit 1
elif [ "$1" == "create" ] && [ ! -d /opt/lampp/htdocs/NewProject ]; then
cd ~
cd /opt/lampp/htdocs
composer create-project laravel/laravel NewProject
cd NewProject
npm install
composer install
php artisan key:generate
cd ~
mkdir /opt/lampp/htdocs/NewProject/resources/scss
touch /opt/lampp/htdocs/NewProject/resources/scss/app.scss
cd /opt/lampp/htdocs/NewProject
php artisan storage:link
npm install sass
cd ~
sudo /opt/lampp/lampp start
cd /opt/lampp/htdocs/NewProject
echo "+---------------------------------------------------------+"
echo "|.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.|"
echo "| Create New Laravel Successfully _ Made by Le Hoang Cau  |"
echo "|                                                         |"
echo "|--> Web-Server:     [http://127.0.0.1:8000]              |"
echo "|                                                         |"
echo "|--> Phpmyadmin:     [http://127.0.0.1/phpmyadmin]        |"
echo "|                                                         |"
echo "|--> Source-project: [/opt/lampp/htdocs/NewProject]       |"
echo "|                                                         |"
echo "+---------------------------------------------------------+"
php artisan serve
exit 1
elif [ "$1" == "start" ]; then
    sudo /opt/lampp/lampp start
    php artisan serve
    exit 1
elif [ "$1" == "stop" ]; then
    sudo /opt/lampp/lampp stop
    echo "Successfully"
    exit 1
elif [ "$1" == "help" ]; then
echo "+---------------------------------------------------------+"
echo "|.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.*.^.|"
echo "| Create New Laravel Successfully _ Made by Le Hoang Cau  |"
echo "|                                                         |"
echo "|--> 1hc new:                          create new project |"
echo "|                                                         |"
echo "|--> 1hc start(run in source_project): start server       |"
echo "|                                                         |"
echo "|--> 1hc stop:                         stop server        |"
echo "|                                                         |"
echo "+---------------------------------------------------------+"
    exit 1
else
    echo "Unknown command: $1"
    exit 1
fi
